# 一个被所有 ROOT 消费者继承的运行库目标。纯 common 构建不需要 ROOT。
add_library(eff_runtime INTERFACE)
if(NOT EFF_BUILD_SIMULATION AND NOT EFF_BUILD_MERGER)
    return()
endif()
if(CMAKE_CROSSCOMPILING)
    message(FATAL_ERROR "Dependency startup checks require a native build on the target cluster OS.")
endif()

function(eff_imported_location TARGET_NAME OUTPUT)
    get_target_property(LOCATION "${TARGET_NAME}" IMPORTED_LOCATION)
    if(NOT LOCATION)
        get_target_property(CONFIGS "${TARGET_NAME}" IMPORTED_CONFIGURATIONS)
        foreach(CONFIG IN LISTS CONFIGS)
            get_target_property(LOCATION "${TARGET_NAME}" "IMPORTED_LOCATION_${CONFIG}")
            if(LOCATION)
                break()
            endif()
        endforeach()
    endif()
    if(NOT EXISTS "${LOCATION}")
        message(FATAL_ERROR "Cannot resolve the installed library for ${TARGET_NAME}: ${LOCATION}")
    endif()
    set(${OUTPUT} "${LOCATION}" PARENT_SCOPE)
endfunction()

eff_imported_location(ROOT::Core EFF_ROOT_CORE)
get_filename_component(EFF_ROOT_LIBDIR "${EFF_ROOT_CORE}" DIRECTORY)
execute_process(COMMAND "${EFF_ROOT_CONFIG}" --libdir OUTPUT_VARIABLE EFF_CONFIG_ROOT_LIBDIR
    OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY TIMEOUT 10)
get_filename_component(EFF_EXPECTED_ROOT_LIBDIR "${EFF_CONFIG_ROOT_LIBDIR}" REALPATH)
get_filename_component(EFF_ACTUAL_ROOT_LIBDIR "${EFF_ROOT_LIBDIR}" REALPATH)
if(NOT EFF_EXPECTED_ROOT_LIBDIR STREQUAL EFF_ACTUAL_ROOT_LIBDIR)
    message(FATAL_ERROR "root-config and ROOT CMake targets use different installations. Set ROOT_DIR and EFF_ROOT_CONFIG consistently.")
endif()

set(EFF_CHECK_LIBS ROOT::Core ROOT::RIO ROOT::Tree ROOT::TreePlayer)
set(EFF_CHECK_DEFINES "")
set(EFF_RUNTIME_DIRS "${EFF_ROOT_LIBDIR}")
if(EFF_BUILD_SIMULATION)
    eff_imported_location(Geant4::G4run EFF_G4_RUN)
    get_filename_component(EFF_G4_LIBDIR "${EFF_G4_RUN}" DIRECTORY)
    execute_process(COMMAND "${EFF_GEANT4_CONFIG}" --prefix OUTPUT_VARIABLE EFF_G4_PREFIX
        OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY TIMEOUT 10)
    get_filename_component(EFF_G4_ACTUAL "${EFF_G4_LIBDIR}" REALPATH)
    get_filename_component(EFF_G4_PREFIX_REAL "${EFF_G4_PREFIX}" REALPATH)
    string(FIND "${EFF_G4_ACTUAL}/" "${EFF_G4_PREFIX_REAL}/" EFF_G4_PREFIX_POSITION)
    if(NOT EFF_G4_PREFIX_POSITION EQUAL 0)
        message(FATAL_ERROR "Geant4 CMake libraries and geant4-config are from different installations.")
    endif()
    get_filename_component(EFF_HEALPIX_LIBDIR "${HEALPIX_LIBRARY}" DIRECTORY)
    # 编译期选中的 Geant4 优先，避免继承旧 LD_LIBRARY_PATH 中的 Geant4 10.x。
    list(PREPEND EFF_RUNTIME_DIRS "${EFF_G4_LIBDIR}")
    list(APPEND EFF_RUNTIME_DIRS "${EFF_HEALPIX_LIBDIR}")
    list(APPEND EFF_CHECK_LIBS eff_healpix Geant4::G4run Geant4::G4event Geant4::G4processes
        Geant4::G4digits_hits Geant4::G4particles Geant4::G4geometry Geant4::G4materials Geant4::G4tracking)
    list(APPEND EFF_CHECK_DEFINES -DEFF_PROBE_SIMULATION)
endif()

set(EFF_CXX_RUNTIME_LIBRARY "" CACHE FILEPATH "Optional compatible libstdc++.so.6; otherwise checked automatically")
set(EFF_PROBE_TIMEOUT_SECONDS 45 CACHE STRING "Dependency probe timeout; a timeout is not a successful check")
if(NOT EFF_PROBE_TIMEOUT_SECONDS MATCHES "^[1-9][0-9]*$" OR EFF_PROBE_TIMEOUT_SECONDS GREATER 600)
    message(FATAL_ERROR "EFF_PROBE_TIMEOUT_SECONDS must be an integer from 1 to 600.")
endif()
set(EFF_LOG "${CMAKE_BINARY_DIR}/dependency-check.log")
file(WRITE "${EFF_LOG}" "Compiler: ${CMAKE_CXX_COMPILER}\nStandard: C++${CMAKE_CXX_STANDARD}\nROOT: ${EFF_ROOT_LIBDIR}\n")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/dependency-check")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    find_program(EFF_LDD ldd REQUIRED)
endif()

function(eff_loaded_matches TEXT NAME EXPECTED OUTPUT)
    string(REGEX MATCH "${NAME}[^ \n\r]* => ([^ \n\r]+)" MATCHED "${TEXT}")
    if(NOT MATCHED)
        set(${OUTPUT} FALSE PARENT_SCOPE)
        return()
    endif()
    get_filename_component(LOADED "${CMAKE_MATCH_1}" REALPATH)
    get_filename_component(WANTED "${EXPECTED}" REALPATH)
    if(LOADED STREQUAL WANTED)
        set(${OUTPUT} TRUE PARENT_SCOPE)
    else()
        file(APPEND "${EFF_LOG}" "Library mismatch: ${NAME}: loaded ${LOADED}; wanted ${WANTED}\n")
        set(${OUTPUT} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(eff_run_probe PROBE LIBRARY_PATH OUTPUT REASON)
    # 直接写文件，使程序运行期间也能 tail 日志；超时后仍保留已刷新的阶段消息。
    set(STDOUT_FILE "${CMAKE_BINARY_DIR}/dependency-check/probe.stdout.log")
    set(STDERR_FILE "${CMAKE_BINARY_DIR}/dependency-check/probe.stderr.log")
    message(STATUS "Running dependency probe (timeout ${EFF_PROBE_TIMEOUT_SECONDS}s); stages: ${STDERR_FILE}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "LD_LIBRARY_PATH=${LIBRARY_PATH}" "LD_BIND_NOW=1"
        "OMP_NUM_THREADS=1" "OPENBLAS_NUM_THREADS=1" "${PROBE}"
        RESULT_VARIABLE RUN_STATUS OUTPUT_FILE "${STDOUT_FILE}" ERROR_FILE "${STDERR_FILE}"
        TIMEOUT ${EFF_PROBE_TIMEOUT_SECONDS})
    file(READ "${STDOUT_FILE}" RUN_OUT)
    file(READ "${STDERR_FILE}" RUN_ERR)
    file(APPEND "${EFF_LOG}" "Startup status: ${RUN_STATUS}\n${RUN_OUT}\n${RUN_ERR}\n")
    set(PASSED FALSE)
    if(RUN_STATUS STREQUAL "0")
        set(PASSED TRUE)
        set(FAILURE "")
    elseif(RUN_STATUS MATCHES "[Tt]imeout")
        # CMake 用分号分隔 list；原日志不变，只在终端摘要里替换成逗号。
        string(REPLACE ";" "," STAGE_TEXT "${RUN_ERR}")
        string(REGEX MATCHALL "\\[dependency-probe\\][^\r\n]*" STAGES "${STAGE_TEXT}")
        if(STAGES)
            list(GET STAGES -1 LAST_STAGE)
        else()
            set(LAST_STAGE "No main-entry marker was captured; main entry is not confirmed.")
        endif()
        set(FAILURE "Probe timed out after ${EFF_PROBE_TIMEOUT_SECONDS}s AFTER successful linking.\nLast stage: ${LAST_STAGE}\nThis does not establish compiler incompatibility. See ${STDERR_FILE} and ${EFF_LOG}.")
    else()
        set(FAILURE "Probe failed AFTER successful linking (status: ${RUN_STATUS}). See ${STDERR_FILE} and ${EFF_LOG}.")
    endif()
    set(${OUTPUT} ${PASSED} PARENT_SCOPE)
    set(${REASON} "${FAILURE}" PARENT_SCOPE)
endfunction()

function(eff_check_runtime RUNTIME OUTPUT)
    set(LIBS ${EFF_CHECK_LIBS})
    set(DIRS ${EFF_RUNTIME_DIRS})
    if(RUNTIME)
        list(APPEND LIBS "${RUNTIME}")
        get_filename_component(RUNTIME_DIR "${RUNTIME}" DIRECTORY)
        list(APPEND DIRS "${RUNTIME_DIR}")
    endif()
    list(REMOVE_DUPLICATES DIRS)
    list(JOIN DIRS ":" LIBRARY_PATH)
    if(NOT "$ENV{LD_LIBRARY_PATH}" STREQUAL "")
        string(APPEND LIBRARY_PATH ":$ENV{LD_LIBRARY_PATH}")
    endif()
    set(PROBE "${CMAKE_BINARY_DIR}/dependency-check/probe${CMAKE_EXECUTABLE_SUFFIX}")
    # 每次重新检查，不能继承上次成功的缓存结果。
    unset(EFF_PROBE_LINKS CACHE)
    try_compile(EFF_PROBE_LINKS "${CMAKE_BINARY_DIR}/dependency-check/compile"
        "${EFF_PROJECT_ROOT}/cmake/dependency_probe.cpp"
        COMPILE_DEFINITIONS ${EFF_CHECK_DEFINES}
        LINK_LIBRARIES ${LIBS}
        CXX_STANDARD ${CMAKE_CXX_STANDARD} CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF
        COPY_FILE "${PROBE}" OUTPUT_VARIABLE LINK_LOG)
    file(APPEND "${EFF_LOG}" "\n=== Runtime override: ${RUNTIME} ===\n${LINK_LOG}\n")
    file(APPEND "${EFF_LOG}" "Probe LD_LIBRARY_PATH: ${LIBRARY_PATH}\n")
    set(PASSED FALSE)
    set(FAILURE "Probe compilation/linking failed. See ${EFF_LOG} for the compiler/linker error.")
    if(EFF_PROBE_LINKS)
        # 先核对动态库；即使后面的 ROOT 初始化卡住，也不会再丢失这项诊断。
        set(PASSED TRUE)
        set(FAILURE "Dynamic-library path/symbol check failed after linking. See ${EFF_LOG}.")
        if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
            execute_process(COMMAND "${CMAKE_COMMAND}" -E env "LD_LIBRARY_PATH=${LIBRARY_PATH}"
                "${EFF_LDD}" -r "${PROBE}" OUTPUT_VARIABLE LDD_OUT ERROR_VARIABLE LDD_ERR
                RESULT_VARIABLE LDD_STATUS TIMEOUT 30)
            file(APPEND "${EFF_LOG}" "ldd -r status: ${LDD_STATUS}\n${LDD_OUT}\n${LDD_ERR}\n")
            eff_loaded_matches("${LDD_OUT}" "libCore\\.so" "${EFF_ROOT_CORE}" ROOT_MATCH)
            if(NOT LDD_STATUS STREQUAL "0" OR NOT ROOT_MATCH OR "${LDD_OUT}${LDD_ERR}" MATCHES "not found|undefined symbol")
                set(PASSED FALSE)
            endif()
            if(EFF_BUILD_SIMULATION)
                eff_loaded_matches("${LDD_OUT}" "libG4run\\.so" "${EFF_G4_RUN}" G4_MATCH)
                if(NOT G4_MATCH)
                    set(PASSED FALSE)
                endif()
            endif()
            if(RUNTIME)
                eff_loaded_matches("${LDD_OUT}" "libstdc\\+\\+\\.so" "${RUNTIME}" CXX_MATCH)
                if(NOT CXX_MATCH)
                    set(PASSED FALSE)
                endif()
            endif()
        endif()
        if(PASSED)
            eff_run_probe("${PROBE}" "${LIBRARY_PATH}" PASSED FAILURE)
        endif()
        if(PASSED)
            message(STATUS "Dependency startup check passed: memory read, library checks and normal exit.")
        endif()
    endif()
    file(APPEND "${EFF_LOG}" "Check passed: ${PASSED}\n${FAILURE}\n")
    set(${OUTPUT} ${PASSED} PARENT_SCOPE)
    set(EFF_CHECK_FAILURE "${FAILURE}" PARENT_SCOPE)
endfunction()

if(EFF_CXX_RUNTIME_LIBRARY AND NOT EXISTS "${EFF_CXX_RUNTIME_LIBRARY}")
    message(FATAL_ERROR "EFF_CXX_RUNTIME_LIBRARY does not exist: ${EFF_CXX_RUNTIME_LIBRARY}")
endif()
eff_check_runtime("${EFF_CXX_RUNTIME_LIBRARY}" EFF_CHECK_PASSED)
set(EFF_SELECTED_CXX_RUNTIME "${EFF_CXX_RUNTIME_LIBRARY}")
if(NOT EFF_CHECK_PASSED AND NOT EFF_CXX_RUNTIME_LIBRARY AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
    # 常见情况：系统 GCC12 + Conda ROOT。先试 ROOT 同目录提供的新版 libstdc++，
    # 不覆盖系统库、不安装软件，也不把 -std=c++20 误当成 ABI 修复。
    set(EFF_CANDIDATE "${EFF_ROOT_LIBDIR}/libstdc++.so.6")
    if(EXISTS "${EFF_CANDIDATE}")
        message(STATUS "Default link/startup failed; testing ROOT's libstdc++: ${EFF_CANDIDATE}")
        eff_check_runtime("${EFF_CANDIDATE}" EFF_CHECK_PASSED)
        if(EFF_CHECK_PASSED)
            set(EFF_SELECTED_CXX_RUNTIME "${EFF_CANDIDATE}")
        endif()
    endif()
endif()
if(NOT EFF_CHECK_PASSED)
    message(FATAL_ERROR "Dependency check FAILED.\n${EFF_CHECK_FAILURE}\nNo simulation was started. Do not run make all/run-local until configuration succeeds.")
endif()
if(EFF_SELECTED_CXX_RUNTIME)
    target_link_libraries(eff_runtime INTERFACE "${EFF_SELECTED_CXX_RUNTIME}")
    get_filename_component(EFF_CXX_RUNTIME_DIR "${EFF_SELECTED_CXX_RUNTIME}" DIRECTORY)
    list(APPEND EFF_RUNTIME_DIRS "${EFF_CXX_RUNTIME_DIR}")
    message(STATUS "Pinned C++ runtime: ${EFF_SELECTED_CXX_RUNTIME}")
endif()
list(REMOVE_DUPLICATES EFF_RUNTIME_DIRS)
foreach(EFF_DIR IN LISTS EFF_RUNTIME_DIRS)
    if(EFF_DIR MATCHES "['\n\r]")
        message(FATAL_ERROR "Library path cannot contain a quote or newline: ${EFF_DIR}")
    endif()
endforeach()
list(JOIN EFF_RUNTIME_DIRS ":" EFF_RUNTIME_PATH)
if(UNIX)
    # 工作流通过同一套 LD_LIBRARY_PATH 启动；rpath 也支持直接启动常见安装。
    foreach(EFF_DIR IN LISTS EFF_RUNTIME_DIRS)
        target_link_options(eff_runtime INTERFACE "-Wl,-rpath,${EFF_DIR}")
    endforeach()
endif()
