# 优先尊重用户指定的 *_DIR、CMAKE_PREFIX_PATH；其后才补常见安装位置。
# 只检查有限目录，绝不递归扫描 HOME、共享磁盘或 /cvmfs。
set(EFF_PREFIX_HINTS ${CMAKE_PREFIX_PATH})
if(DEFINED ENV{CMAKE_PREFIX_PATH})
    file(TO_CMAKE_PATH "$ENV{CMAKE_PREFIX_PATH}" EFF_ENV_PREFIXES)
    list(APPEND EFF_PREFIX_HINTS ${EFF_ENV_PREFIXES})
endif()
foreach(EFF_ENV_NAME EIID_DEPS_PREFIX CONDA_PREFIX VIRTUAL_ENV)
    if(DEFINED ENV{${EFF_ENV_NAME}} AND NOT "$ENV{${EFF_ENV_NAME}}" STREQUAL "")
        list(APPEND EFF_PREFIX_HINTS "$ENV{${EFF_ENV_NAME}}")
    endif()
endforeach()
if(DEFINED ENV{HOME})
    foreach(EFF_ENV_ROOT miniconda3 miniforge3 anaconda3 micromamba .conda)
        list(APPEND EFF_PREFIX_HINTS "$ENV{HOME}/${EFF_ENV_ROOT}/envs/root-env")
    endforeach()
endif()
foreach(EFF_TOOL ROOT_CONFIG GEANT4_CONFIG)
    if(DEFINED ENV{${EFF_TOOL}} AND NOT "$ENV{${EFF_TOOL}}" STREQUAL "")
        # 显式配置失效应立即说明，不能悄悄换另一套库。
        execute_process(COMMAND "$ENV{${EFF_TOOL}}" --prefix OUTPUT_VARIABLE EFF_TOOL_PREFIX
            OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE EFF_TOOL_STATUS TIMEOUT 10)
        if(NOT EFF_TOOL_STATUS STREQUAL "0")
            message(FATAL_ERROR "${EFF_TOOL} failed: $ENV{${EFF_TOOL}}")
        endif()
        list(PREPEND EFF_PREFIX_HINTS "${EFF_TOOL_PREFIX}")
        set(EFF_${EFF_TOOL} "$ENV{${EFF_TOOL}}" CACHE FILEPATH "Explicit config tool")
    endif()
endforeach()
file(GLOB EFF_OPT_PREFIXES LIST_DIRECTORIES true
    "/opt/geant4/*-install" "/opt/geant4.*/*-install" "/opt/Geant4/*-install")
list(SORT EFF_OPT_PREFIXES COMPARE NATURAL ORDER DESCENDING)
list(APPEND EFF_PREFIX_HINTS ${EFF_OPT_PREFIXES})
foreach(EFF_PREFIX IN LISTS EFF_PREFIX_HINTS)
    if(IS_DIRECTORY "${EFF_PREFIX}")
        list(APPEND CMAKE_PREFIX_PATH "${EFF_PREFIX}")
    endif()
endforeach()
list(REMOVE_DUPLICATES CMAKE_PREFIX_PATH)
message(STATUS "Dependency search prefixes: ${CMAKE_PREFIX_PATH}")
